apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-rest-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-rest-service
  template:
    metadata:
      labels:
        app: kafka-rest-service
    spec:
      initContainers:
        - name: wait-for-zookeeper
          image: busybox
          command: [ 'sh', '-c', "until nc -z zookeeper 2181; do echo waiting for zookeeper; sleep 2; done" ]
      containers:
        - name: kafka-rest-service
          image: confluentinc/cp-kafka:latest
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:9092"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-rest-service:9092"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-rest-service
spec:
  selector:
    app: kafka-rest-service
  ports:
    - port: 9092
      targetPort: 9092
      protocol: TCP