server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/IMAGE_SERVICE
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    root: INFO