server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://mongo_db:27017/IMAGE_SERVICE
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  boot:
    admin:
      client:
        url: http://localhost:9090
        username: admin
        password: admin

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topic:
      image-saved: image.saved

logging:
  level:
    root: INFO